!!python/object/new:easydict.EasyDict
dictitems:
  DATA_DIRECTORY_SOURCE: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/SynthiaSeq/SEQS-04-DAWN
  DATA_DIRECTORY_TARGET: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/Cityscapes
  DATA_LIST_SOURCE: tps/dataset/SynthiaSeq_list/train.txt
  DATA_LIST_TARGET: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/tps/dataset/CityscapesSeq_list/{}.txt
  EXP_NAME: SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
  EXP_ROOT: &id020 !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - sysmanager
  - customer
  - Desktop
  - ZZ
  - FMFSemi
  - TransferLearning
  - examples
  - domain_adaptation
  - udass
  - video_udass
  - VIDEO
  - experiments_result
  EXP_ROOT_LOGS: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/logs
  EXP_ROOT_SNAPSHOT: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/snapshots
  NUM_CLASSES: 12
  NUM_WORKERS: 4
  N_SEGMENTS: 4
  SOURCE: SynthiaSeq
  TARGET: CityscapesSeq
  TENSORBOARD_DIR: ''
  TEST: &id021 !!python/object/new:easydict.EasyDict
    dictitems:
      BATCH_SIZE_TARGET: 1
      DAVSS_DSF_cd_ablation_24: &id001
      - /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_tps/TPS/pretrained_models
      DAVSS_DSF_cd_ablation_24_former: &id002
      - /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_tps/TPS/pretrained_models
      DAVSS_DSF_cd_ablation_31: &id003
      - /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_tps/TPS/pretrained_models
      DAVSS_DSF_cd_ablation_31_former: &id004
      - /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_tps/TPS/pretrained_models
      IMG_MEAN: &id005 !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id014 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - &id015 !!python/object/apply:numpy.dtype
          args:
          - f4
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          lAPQQmlW6UKbW/VC
      INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
      INPUT_SIZE_TARGET: &id006
      - 1024
      - 512
      INTERVAL: 1
      MODE: video_best
      MODEL: &id007
      - ACCEL_DeepLabv2
      MODEL_WEIGHT: &id008
      - 1.0
      MULTI_LEVEL: &id009
      - true
      OUTPUT_SIZE_TARGET: &id010
      - 2048
      - 1024
      RESTORE_FROM: &id011
      - ''
      RESTORE_FROM_prototype: &id012
      - ''
      SET_TARGET: val
      SNAPSHOT_DIR: &id013
      - ''
      SNAPSHOT_MAXITER: 40000
      SNAPSHOT_START_ITER: 1000
      SNAPSHOT_STEP: 1000
      WAIT_MODEL: true
      flow_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_val
    state:
      BATCH_SIZE_TARGET: 1
      DAVSS_DSF_cd_ablation_24: *id001
      DAVSS_DSF_cd_ablation_24_former: *id002
      DAVSS_DSF_cd_ablation_31: *id003
      DAVSS_DSF_cd_ablation_31_former: *id004
      IMG_MEAN: *id005
      INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
      INPUT_SIZE_TARGET: *id006
      INTERVAL: 1
      MODE: video_best
      MODEL: *id007
      MODEL_WEIGHT: *id008
      MULTI_LEVEL: *id009
      OUTPUT_SIZE_TARGET: *id010
      RESTORE_FROM: *id011
      RESTORE_FROM_prototype: *id012
      SET_TARGET: val
      SNAPSHOT_DIR: *id013
      SNAPSHOT_MAXITER: 40000
      SNAPSHOT_START_ITER: 1000
      SNAPSHOT_STEP: 1000
      WAIT_MODEL: true
      flow_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_val
  TRAIN: &id022 !!python/object/new:easydict.EasyDict
    dictitems:
      BATCH_SIZE: 1
      BATCH_SIZE_SOURCE: 1
      BATCH_SIZE_TARGET: 1
      DA_METHOD: TPS
      EARLY_STOP: 40000
      IGNORE_LABEL: 255
      IMG_MEAN: &id016 !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id014
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - *id015
        - false
        - !!binary |
          lAPQQmlW6UKbW/VC
      INFO_SOURCE: ''
      INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
      INPUT_SIZE_SOURCE: &id017
      - 1280
      - 640
      INPUT_SIZE_TARGET: &id018
      - 1024
      - 512
      INTERVAL: 1
      LAMBDA_SEG_AUX: 0.1
      LAMBDA_SEG_MAIN: 1.0
      LAMBDA_T: 1.0
      LEARNING_RATE: 0.00025
      MAX_ITERS: 250000
      MODEL: ACCEL_DeepLabv2
      MOMENTUM: 0.9
      MULTI_LEVEL: true
      POWER: 0.9
      RANDOM_SEED: 1234
      RESTORE_FROM: pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
      RESTORE_FROM_synthia: pretrained_models/tps_syn2city_pretrained.pth
      RESTORE_FROM_viper: pretrained_models/tps_viper2city_pretrained.pth
      SAVE_PRED_EVERY: 1000
      SCALING_RATIO: &id019
      - 0.8
      - 1.2
      SET_SOURCE: train
      SET_TARGET: train
      SNAPSHOT_DIR: ''
      SNAPSHOT_DIR_DSP_CD: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/snapshots/SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
      TENSORBOARD_LOGDIR_CD: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/logs/tensorboard/SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
      TENSORBOARD_VIZRATE: 1000
      THRESHOLD: 0.0
      WEIGHT_DECAY: 0.0005
      flow_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_train
      flow_path_src: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_synthiaseq_train
    state:
      BATCH_SIZE: 1
      BATCH_SIZE_SOURCE: 1
      BATCH_SIZE_TARGET: 1
      DA_METHOD: TPS
      EARLY_STOP: 40000
      IGNORE_LABEL: 255
      IMG_MEAN: *id016
      INFO_SOURCE: ''
      INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
      INPUT_SIZE_SOURCE: *id017
      INPUT_SIZE_TARGET: *id018
      INTERVAL: 1
      LAMBDA_SEG_AUX: 0.1
      LAMBDA_SEG_MAIN: 1.0
      LAMBDA_T: 1.0
      LEARNING_RATE: 0.00025
      MAX_ITERS: 250000
      MODEL: ACCEL_DeepLabv2
      MOMENTUM: 0.9
      MULTI_LEVEL: true
      POWER: 0.9
      RANDOM_SEED: 1234
      RESTORE_FROM: pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
      RESTORE_FROM_synthia: pretrained_models/tps_syn2city_pretrained.pth
      RESTORE_FROM_viper: pretrained_models/tps_viper2city_pretrained.pth
      SAVE_PRED_EVERY: 1000
      SCALING_RATIO: *id019
      SET_SOURCE: train
      SET_TARGET: train
      SNAPSHOT_DIR: ''
      SNAPSHOT_DIR_DSP_CD: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/snapshots/SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
      TENSORBOARD_LOGDIR_CD: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/logs/tensorboard/SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
      TENSORBOARD_VIZRATE: 1000
      THRESHOLD: 0.0
      WEIGHT_DECAY: 0.0005
      flow_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_train
      flow_path_src: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_synthiaseq_train
  alpha_mix: 0.5
  dsp_hard_loss: true
  ema_w: 0.5
  generate_tcsm_synthia_path: ''
  generate_threshold_path: experiments_result/generate_synthina
  ignore_index: 250
  lamda: 1.0
  loss_cts_W: 0.5
  pixel_weight: threshold_uniform
  project: &id023 !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - sysmanager
  - customer
  - Desktop
  - ZZ
  - FMFSemi
  - TransferLearning
  - examples
  - domain_adaptation
  - udass
  - video_udass
  - VIDEO
  proto_consistW: 10.0
  proto_momentum: 0.1
  proto_resume: false
  proto_temperature: 1.0
  prototype_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/prototype
  regular_type: MRKLD
  regular_w: 0.1
  tar_loss_weight: 0.6
  tensorboard: true
  train_thred: 0.0
state:
  DATA_DIRECTORY_SOURCE: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/SynthiaSeq/SEQS-04-DAWN
  DATA_DIRECTORY_TARGET: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/Cityscapes
  DATA_LIST_SOURCE: tps/dataset/SynthiaSeq_list/train.txt
  DATA_LIST_TARGET: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/tps/dataset/CityscapesSeq_list/{}.txt
  EXP_NAME: SynthiaSeq2CityscapesSeq_ACCEL_DeepLabv2_TPS_DAVSS_DSF_cd_ablation_24
  EXP_ROOT: *id020
  EXP_ROOT_LOGS: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/logs
  EXP_ROOT_SNAPSHOT: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/snapshots
  NUM_CLASSES: 12
  NUM_WORKERS: 4
  N_SEGMENTS: 4
  SOURCE: SynthiaSeq
  TARGET: CityscapesSeq
  TENSORBOARD_DIR: ''
  TEST: *id021
  TRAIN: *id022
  alpha_mix: 0.5
  dsp_hard_loss: true
  ema_w: 0.5
  generate_tcsm_synthia_path: ''
  generate_threshold_path: experiments_result/generate_synthina
  ignore_index: 250
  lamda: 1.0
  loss_cts_W: 0.5
  pixel_weight: threshold_uniform
  project: *id023
  proto_consistW: 10.0
  proto_momentum: 0.1
  proto_resume: false
  proto_temperature: 1.0
  prototype_path: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/udass/video_udass/VIDEO/experiments_result/prototype
  regular_type: MRKLD
  regular_w: 0.1
  tar_loss_weight: 0.6
  tensorboard: true
  train_thred: 0.0
