SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: tps/dataset/SynthiaSeq_list/train.txt
NUM_CLASSES: 12
generate_threshold_path: experiments_result/generate_synthina
DATA_DIRECTORY_TARGET: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/data/Cityscapes

TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  LAMBDA_T: 1.0
  flow_path: '/home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_train'
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: /home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_synthiaseq_train
  DA_METHOD: TPS
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
  SAVE_PRED_EVERY: 1000 # 100

TEST:
  flow_path: '/home/sysmanager/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/data/estimated_optical_flow_cityscapes_seq_val'
  MODE: video_best # {'video_single', 'video_best', 'video_best_tcsm'}
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SNAPSHOT_STEP: 1000 # 100
  SNAPSHOT_START_ITER: 1000 # 100
